In [2]:
#fasttext文本预测模型结构
#输入层：输入文本被转换为词向量表示，通常使用预训练的词向量（如Word2Vec或GloVe）或者随机初始化的词向量。
#隐藏层：FastText模型的隐藏层通常是一个简单的平均池化层，它将输入文本的词向量进行平均，以获得文本的整体表示。
#输出层：输出层是一个全连接层，通常使用softmax激活函数来进行多分类任务。输出层的大小取决于分类任务的类别数量。

#模型训练的过程
#1.获取数据
#2.训练集和测试集的划分
#3.训练模型
#4.模型预测和评估

#5.模型调优
#6.模型部署和保存

#代码示例
#import fasttext
#训练模型
#model = fasttext.train_supervised(input="train.txt", epoch=25, lr=1.0, wordNgrams=2, verbose=2, minCount=1)
#评估模型
#result = model.test("test.txt")
#print("P@1:", result[1]) 精确率
#print("R@1:", result[2]) 召回率

#数据未处理，训练效果很差

#模型调优思路
#1.原始数据处理，如文本清洗、分词、去除停用词等。
#2.增加训练轮数,如将epoch从25增加到50或更多，以便模型有更多机会学习数据中的模式。
#3.调整学习率,如将lr从1.0调整为0.5或0.1，以便模型更稳定地收敛。
#4.增加n-gram特征,如将wordNgrams从2增加到3或4，以捕捉更多的上下文信息。
#5.修改损失计算方式,如将loss从softmax调整为hierarchical softmax，以提高训练效率和模型性能。
#6.自动超参数调优,如使用网格搜索或随机搜索来寻找最佳的超参数组合。

#实际生产中的多标签多分类问题
#对应的损失计算函数为ova,即one-vs-all，适用于多标签分类任务。在这种情况下，模型会为每个标签独立地计算一个二分类的损失函数，以判断该标签是否存在于输入文本中。这种方法允许模型同时预测多个标签，并且在训练过程中能够更好地处理标签之间的相关性。
#将每个标签转化为一个独立的二分类问题

#输出标签的时候，模型会为每个标签输出一个概率值，表示该标签存在的可能性。通常情况下，可以设置一个阈值（如0.5）来判断是否将该标签分配给输入文本。如果某个标签的概率值超过了这个阈值，就认为该标签存在于输入文本中；否则，就认为该标签不存在。这种方法允许模型同时预测多个标签，并且在训练过程中能够更好地处理标签之间的相关性。可以设置阈值以输出多标签分类结果



In [3]:
#词向量迁移
#fasttext提供了预训练的词向量，可以直接使用这些词向量来初始化模型的输入层，从而加速模型的训练过程并提高模型的性能。使用预训练的词向量可以帮助模型更好地理解文本中的语义关系，从而提高分类的准确性。
#使用预训练的词向量
#model = fasttext.train_supervised(input="train.txt", epoch=25, lr=1.0, wordNgrams=2, verbose=2, minCount=1, pretrainedVectors="cc.en.300.vec")


In [4]:
#迁移学习
#1.预训练模型：首先，在一个大规模的文本数据集上预训练一个fasttext模型，以学习通用的文本表示。在nlp任务中，预训练模型可以捕捉到丰富的语义信息和上下文关系，这些信息对于下游任务非常有用。

#2.微调模型：根据给定的训练数据集，对预训练模型进行微调。微调的过程包括调整模型的参数和结构，以适应特定的分类任务。可以通过增加新的输出层来适应新的标签类别，或者调整现有的输出层以适应新的数据分布。


In [5]:
#transformers库的使用
#huggingface的transformers库提供了丰富的预训练模型和工具，可以用于文本分类任务。以下是一个使用transformers库进行文本分类的示例，支持模型的further pretraining和下游任务的fine-tuning:

#transformers库的应用结构
#1.pipline: transformers库提供了一个pipeline接口，可以方便地进行文本分类任务。通过pipeline接口，可以快速加载预训练模型并进行文本分类。
#2.AutoModel和AutoTokenizer: transformers库提供了AutoModel和AutoTokenizer类，可以根据预训练模型的名称自动加载相应的模型和分词器。这使得使用预训练模型变得非常简单。

In [6]:
#pipline实现
import torch
from transformers import pipeline
#pipeline的功能是提供一个简单的接口来使用预训练模型进行各种自然语言处理任务，如文本分类、命名实体识别、文本生成等。通过pipeline接口，用户可以快速加载预训练模型并进行相应的任务，而无需关心底层的模型细节和实现。这使得使用预训练模型变得非常方便和高效。

model=pipeline(task="text-classification",model='./chinese-sentiment')
input="这个电影不好看！"
result=model(input)
print(result)

D:\Anaconda_envs\envs\aitest01\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
D:\Anaconda_envs\envs\aitest01\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] 找不到指定的程序。'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


KeyboardInterrupt: 

In [19]:
#特征提取任务
#特征提取任务是指从文本中提取有用的特征，以便进行后续的分析或建模。在自然语言处理（NLP）中，特征提取是一个重要的步骤，可以帮助模型更好地理解文本的语义和结构。比如获取词向量。

#不带任务头输出：
#含义：当使用transformers库进行特征提取任务时，如果不带任务头输出，模型将直接输出文本的特征表示，而不是进行具体的分类或预测。这种方式适用于需要获取文本的向量表示以供后续分析或建模的场景。

#带任务头输出：
#含义：当使用transformers库进行特征提取任务时，如果带任务头输出，模型将输出文本的特征表示，并且还会包含与特定任务相关的信息，如分类标签或预测结果。这种方式适用于需要同时获取文本的特征表示和具体的分类或预测结果的场景。

#一般使用的模型有BERT、RoBERTa、GPT等预训练模型，这些模型在大规模文本数据上进行预训练，能够捕捉到丰富的语义信息和上下文关系，从而提供高质量的特征表示。这些特征表示可以用于各种下游任务，如文本分类、命名实体识别、文本生成等。

#pipeline实现
extraction_model=pipeline(task='feature-extraction',model='./feature_extraction')
input="这个电影不好看！"
output=extraction_model(input)
print(output)
print(torch.tensor(output).shape)
#输出的形状为(1, 10, 768)，其中1表示批次大小，在特征抽取时加上了CLS和SEP标记，表示输入文本的开始和结束；10表示输入文本的长度，包括CLS和SEP标记；768表示每个标记的特征维度，通常是预训练模型的隐藏层大小。这个输出表示输入文本的特征表示，可以用于后续的分析或建模。CLS的特征包含了整个序列的语义特征，可用于文本分类等任务；SEP的特征表示了输入文本的结束，可以用于区分不同的输入文本；其他标记的特征表示了输入文本中每个词的语义特征，可以用于命名实体识别等任务。

Device set to use cpu


[[[0.27485281229019165, 0.5168625712394714, -0.0826059952378273, 0.11148040741682053, 0.8979260921478271, -0.9966261982917786, -0.32361841201782227, -0.44972461462020874, -0.43549737334251404, 0.8731491565704346, -0.07318094372749329, -0.4405328035354614, 0.7084865570068359, -0.3664495646953583, 1.5313044786453247, -0.7738569974899292, 0.4301910996437073, -2.070387601852417, 0.11929823458194733, 0.18108642101287842, -0.32904404401779175, 1.4438210725784302, -0.16494345664978027, -1.0260709524154663, -0.1501755565404892, -0.3126314580440521, -0.5121108293533325, 0.06134692579507828, 0.9374824166297913, 0.9009448885917664, 0.195437490940094, -0.5566280484199524, -0.2447834014892578, -0.5802587270736694, 0.6646757125854492, -0.6312562823295593, 0.15387605130672455, -0.2499752789735794, -0.3606898784637451, -0.1953962743282318, -0.0030732005834579468, 0.055974267423152924, -0.01865769922733307, 1.9960640668869019, 0.7107336521148682, 0.004533328115940094, -0.19877858459949493, 1.1667776107

In [21]:
#完型填空实现（掩码语言模型）
cloze_model=pipeline(task='fill-mask',model='./fill-mask')
input="我[MASK]你！"
output=cloze_model(input)

print(output)

#BERT模型是基于trasformer编码器的预训练语言模型，具有强大的文本理解能力和上下文建模能力。BERT模型在大规模文本数据上进行预训练，能够捕捉到丰富的语义信息和上下文关系，从而提供高质量的特征表示。这些特征表示可以用于各种下游任务，如文本分类、命名实体识别、文本生成等。BERT模型在自然语言处理领域取得了显著的性能提升，并且被广泛应用于各种NLP任务中。

#BERT模型在微调过程中有两个重要问题，第一个是完型填空问题，第二个是下游任务的适应性问题。完型填空问题是指在微调过程中，模型需要处理输入文本中的缺失部分，这些缺失部分通常用特殊的[MASK]标记表示。模型需要根据上下文信息来预测这些缺失部分的内容，从而完成文本的理解和生成。下游任务的适应性问题是指在微调过程中，模型需要适应特定的下游任务，如文本分类、命名实体识别等。这需要模型能够根据下游任务的需求来调整其参数和结构，以便更好地适应特定的任务需求。

Some weights of the model checkpoint at ./fill-mask were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu


[{'score': 0.3343623876571655, 'token': 2695, 'token_str': '愛', 'sequence': '我 愛 你 ！'}, {'score': 0.23178371787071228, 'token': 4263, 'token_str': '爱', 'sequence': '我 爱 你 ！'}, {'score': 0.08480588346719742, 'token': 3221, 'token_str': '是', 'sequence': '我 是 你 ！'}, {'score': 0.06865981966257095, 'token': 6206, 'token_str': '要', 'sequence': '我 要 你 ！'}, {'score': 0.016295885667204857, 'token': 2682, 'token_str': '想', 'sequence': '我 想 你 ！'}]


In [ ]:
#阅读理解问题（抽取式问答任务）
#阅读理解问题是指在自然语言处理领域中，模型需要根据给定的文本内容来回答用户提出的问题。这种任务通常被称为抽取式问答任务，因为模型需要从文本中抽取出与问题相关的信息来生成答案。阅读理解问题的解决方案通常涉及到文本理解、信息抽取和答案生成等多个步骤。通过训练模型来理解文本内容，并根据用户提出的问题来抽取相关的信息，从而生成准确的答案。这种任务在自然语言处理领域具有重要的应用价值，可以用于智能客服、知识问答等场景中。

#实现方法同上

#NER识别问题（token classification任务）
#命名实体识别（NER）问题是指在自然语言处理领域中，模型需要从文本中识别出特定类型的实体，如人名、地名、组织机构等。这种任务通常被称为命名实体识别任务，因为模型需要识别出文本中的命名实体，并将其分类到相应的类别中。命名实体识别问题的解决方案通常涉及到文本理解、特征提取和分类等多个步骤。通过训练模型来理解文本内容，并根据上下文信息来识别出特定类型的实体，从而实现对文本中命名实体的准确识别和分类。这种任务在自然语言处理领域具有重要的应用价值，可以用于信息抽取、知识图谱构建等场景中。

#实现方法同上

In [14]:
#pipeline和AutoModel、AutoTokenizer的区别
#pipeline是transformers库提供的一个高级接口，旨在简化预训练模型的使用。通过pipeline接口，用户可以快速加载预训练模型并进行各种自然语言处理任务，如文本分类、命名实体识别、文本生成等。pipeline接口封装了模型的加载、输入处理和输出处理等步骤，使得使用预训练模型变得非常方便和高效。
#AutoModel和AutoTokenizer是transformers库提供的两个类，用于自动加载预训练模型和分词器。AutoModel类根据预训练模型的名称自动加载相应的模型，而AutoTokenizer类根据预训练模型的名称自动加载相应的分词器。这些类使得使用预训练模型变得非常简单，用户只需要提供预训练模型的名称，就可以轻松地加载相应的模型和分词器，而无需关心底层的实现细节。
import torch

from transformers import AutoModel, AutoTokenizer,AutoConfig
from transformers import AutoModelForSequenceClassification


tokenizer=AutoTokenizer.from_pretrained('./chinese-sentiment') #加载预训练模型的分词器，指定模型的路径为'./chinese-sentiment'，该路径应该包含预训练模型的配置文件和权重文件。通过AutoTokenizer类，可以根据预训练模型的名称自动加载相应的分词器，从而方便地进行文本预处理和特征提取。
model=AutoModelForSequenceClassification.from_pretrained('./chinese-sentiment') #加载预训练模型的权重，指定模型的路径为'./chinese-sentiment'，该路径应该包含预训练模型的配置文件和权重文件。通过AutoModelForSequenceClassification类，可以根据预训练模型的名称自动加载相应的模型，并且该类适用于序列分类任务，如文本分类等。
sentence='喜欢小宝。'
result=tokenizer.encode(text=sentence,return_tensors='pt',padding='max_length',max_length=10,truncation=True) #分词器对句子进行编码，将输入文本转换为模型可以理解的数字表示。encode方法将输入文本转换为一个整数列表，其中每个整数对应于输入文本中的一个标记（token）。这些标记通常是单词、子词或字符，具体取决于分词器的类型和配置。通过encode方法，可以将输入文本转换为模型可以处理的格式，从而进行后续的特征提取和分类等任务。
print(result)
print(type(result))
#文本分类的结果
model.eval() #将模型设置为评估模式，禁用dropout等训练时特有的行为，以确保模型在推理阶段的稳定性和一致性。
output=model(result) #model进行文本分类的前向传播，输入是经过分词器编码后的文本表示。模型会根据输入的文本表示进行计算，并输出分类结果。输出通常包含分类标签的概率分布或直接的分类标签，具体取决于模型的配置和任务需求。通过调用模型的前向传播方法，可以获得文本分类的结果，从而进行后续的分析和应用。
print(output)
print(output.logits) #取出模型输出中的logits部分，logits是模型在分类任务中输出的原始分数，表示每个类别的相对概率。通过查看logits，可以了解模型对不同类别的预测倾向，从而进行进一步的分析和决策。通常情况下，可以使用softmax函数将logits转换为概率分布，以便更直观地理解模型的预测结果。

#预测最终类别
predicted_label=torch.argmax(output.logits,dim=1) #转换为标签
print(predicted_label.item())

tensor([[ 101, 1599, 3614, 2207, 2140,  511,  102,    0,    0,    0]])
<class 'torch.Tensor'>
SequenceClassifierOutput(loss=None, logits=tensor([[-2.4186, -1.2422, -0.0808,  1.2016,  1.3423]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
tensor([[-2.4186, -1.2422, -0.0808,  1.2016,  1.3423]],
       grad_fn=<AddmmBackward0>)
4


In [26]:
#特征提取任务
tokenizer=AutoTokenizer.from_pretrained('./bert-base-chinese') #加载预训练模型的分词器，指定模型的路径为'./feature_extraction'，该路径应该包含预训练模型的配置文件和权重文件。通过AutoTokenizer类，可以根据预训练模型的名称自动加载相应的分词器，从而方便地进行文本预处理和特征提取。)
model=AutoModel.from_pretrained('./bert-base-chinese') #加载预训练模型的权重，指定模型的路径为'./feature_extraction'，该路径应该包含预训练模型的配置文件和权重文件。通过AutoModel类，可以根据预训练模型的名称自动加载相应的模型，并且该类适用于特征提取任务，如文本表示等。)
text=['狗狗好想老婆大人捏','老婆大人好想狗狗捏']
result=tokenizer.encode_plus(text=text,return_tensors='pt',padding='max_length',truncation=True,max_length=10)
#encoder_plus方法中的token_type_ids参数是用于区分输入文本中不同句子或段落的标记。对于单句输入，token_type_ids通常设置为全0；对于双句输入，token_type_ids会根据句子的位置进行区分，例如第一句的token_type_ids设置为全0，第二句的token_type_ids设置为全1。通过使用token_type_ids，模型可以更好地理解输入文本的结构和上下文，从而提高特征提取的效果。,attention_mask参数是用于指示模型在处理输入文本时应该关注哪些标记的掩码。通常情况下，attention_mask中的值为1表示对应的标记是有效的，模型应该关注它；值为0表示对应的标记是无效的，模型应该忽略它。通过使用attention_mask，模型可以更有效地处理输入文本中的不同部分，从而提高特征提取的效果。

print(result)
model.eval()
output=model(**result) #**result表示将result字典中的键值对作为关键字参数传递给模型的前向传播方法。这种方式可以方便地将分词器编码后的文本表示传递给模型进行特征提取。通过使用**操作符，可以将字典中的键值对展开为关键字参数，从而使得代码更加简洁和易读。
print(output)
print(output['last_hidden_state'].shape)

{'input_ids': tensor([[ 101, 4318, 4318, 1962,  102, 5439, 2038, 1920,  782,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-2.6497e-03, -1.0082e-01, -1.9229e-01,  ...,  5.6304e-01,
          -3.7666e-01, -1.4689e-01],
         [-5.3871e-01,  1.2573e-01, -1.4123e-01,  ..., -3.5244e-04,
          -2.0975e-01, -2.6955e-02],
         [-1.1978e-01,  9.8880e-02, -8.9295e-01,  ...,  6.8694e-01,
           3.2661e-01,  2.1138e-01],
         ...,
         [-5.0143e-01, -2.8678e-01, -1.3574e+00,  ...,  9.1272e-01,
          -1.5022e+00,  3.2755e-01],
         [-4.3280e-01, -7.0469e-02, -4.0454e-01,  ..., -4.0474e-01,
          -3.5306e-01,  4.2034e-01],
         [-2.6373e-01,  2.4422e-01, -1.3659e-02,  ...,  1.6737e+00,
          -7.0455e-02, -3.8732e-01]]], grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 0.9998,  0.9980,  1.0000

In [41]:
#bert模型实现完型填空任务
from transformers import BertTokenizer,BertForMaskedLM
tokenizer=BertTokenizer.from_pretrained('./bert-base-chinese')
model=BertForMaskedLM.from_pretrained('./bert-base-chinese')

text='我喜欢[MASK]。'
result=tokenizer.encode_plus(text=text,return_tensors='pt',padding='max_length',truncation=True,max_length=10)
print(result)

model.eval()
output=model(**result)
print(output.logits.shape)
predicted_label=torch.argmax(output.logits[0][4],dim=-1) #取[mask]的位置进行预测
print(predicted_label)
print(tokenizer.convert_ids_to_tokens(predicted_label.item())) #转换为对应的字符

Some weights of the model checkpoint at ./bert-base-chinese were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


{'input_ids': tensor([[ 101, 2769, 1599, 3614,  103,  511,  102,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}
torch.Size([1, 10, 21128])
tensor(872)
你


In [18]:
#迁移学习实践

#微调的方法
#1.加载预训练模型：首先，加载一个预训练的BERT模型，例如BertForSequenceClassification，用于文本分类任务。
#2.准备数据：准备一个文本分类的数据集，包括输入文本和对应的标签。将输入文本进行分词和编码，转换为模型可以处理的格式。
#3.定义损失函数和优化器：选择适当的损失函数（如交叉熵损失）和优化器（如AdamW）来训练模型。
#4.训练模型：使用准备好的数据集对模型进行训练，调整模型的参数以最小化损失函数。可以使用mini-batch训练，并进行多轮迭代。
#5.评估模型：在训练过程中，使用验证集来评估模型的性能，并根据评估结果进行模型调优，例如调整学习率、增加训练轮数等。
#6.保存模型：训练完成后，保存微调后的模型，以便在实际应用中使用。

#导包
import torch
from transformers import BertTokenizer,BertModel
from transformers import AdamW
import time
from datasets import load_dataset  #使用的是huggingface的datasets库来加载数据集，load_dataset函数可以从本地文件或在线数据源加载数据集，并返回一个Dataset对象，方便进行数据处理和模型训练。

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')#设置设备为GPU（如果可用）或CPU，以便在训练过程中使用适当的计算资源。通过torch.device函数，可以根据系统的硬件配置自动选择使用GPU还是CPU，从而提高模型训练的效率和性能。



#加载数据集
train_dataset=load_dataset('csv',data_files='./data/train(1).csv',split='train')
test_dataset=load_dataset('csv',data_files='./data/test(1).csv',split='train')
validation_dataset=load_dataset('csv',data_files='./data/validation.csv',split='train')
print(train_dataset[0:3])

print(len(train_dataset))  #去获取训练集大小
print(test_dataset)


#验证集和训练集的关系：
#验证集和训练集是两个不同的数据集，验证集用于评估模型在训练过程中的性能，而训练集用于训练模型。验证集通常包含与训练集不同的数据样本，以便能够更准确地评估模型的泛化能力。通过使用验证集，可以监控模型在训练过程中的表现，并根据评估结果进行模型调优，以提高模型的性能和泛化能力。


{'label': [1, 1, 0], 'text': ['选择珠江花园的原因就是方便，有电动扶梯直接到达海边，周围餐馆、食廊、商场、超市、摊位一应俱全。酒店装修一般，但还算整洁。 泳池在大堂的屋顶，因此很小，不过女儿倒是喜欢。 包的早餐是西式的，还算丰富。 服务吗，一般', '15.4寸笔记本的键盘确实爽，基本跟台式机差不多了，蛮喜欢数字小键盘，输数字特方便，样子也很美观，做工也相当不错', '房间太小。其他的都一般。。。。。。。。。']}
9600
Dataset({
    features: ['label', 'text'],
    num_rows: 1200
})


In [19]:
#导包和实例化

from torch.utils.data import DataLoader

tokenizer=BertTokenizer.from_pretrained('./bert-base-chinese')
bert_model=BertModel.from_pretrained('./bert-base-chinese')

bert_model=bert_model.to(device)



In [20]:
#实例化dataloader

def collate_fn(data):
    sents=[i['text'] for i in data] #从输入数据中提取文本内容，构建一个包含所有文本的列表sents。这个列表将用于后续的分词和编码操作，以便将文本转换为模型可以处理的格式。
    labels=[i['label'] for i in data] #从输入数据中提取标签内容，构建一个包含所有标签的列表labels。这个列表将用于后续的训练和评估操作，以便将标签转换为模型可以处理的格式。

    #使用分词器对文本进行编码，得到输入ID、注意力掩码和token类型ID等信息。batch_encode_plus方法可以同时处理多个文本，并且支持填充和截断操作，以确保输入文本的长度一致。返回的结果是一个包含编码信息的字典，可以直接用于模型的输入。
    data=tokenizer.batch_encode_plus(sents,padding='max_length',truncation=True,return_tensors='pt',max_length=500,return_length=True)

    input_ids=data['input_ids'] #从编码结果中提取输入ID，构建一个包含所有输入ID的张量input_ids。这个张量将用于模型的输入，以便进行特征提取和分类等任务。

    attention_mask=data['attention_mask'] #从编码结果中提取注意力掩码，构建一个包含所有注意力掩码的张量attention_mask。这个张量将用于模型的输入，以便指示模型在处理输入文本时应该关注哪些标记。

    token_type_ids=data['token_type_ids']   #从编码结果中提取token类型ID，构建一个包含所有token类型ID的张量token_type_ids。这个张量将用于模型的输入，以便区分输入文本中不同句子或段落的标记。

    labels=torch.LongTensor(labels)

    return input_ids,attention_mask,token_type_ids,labels

train_dataloader=DataLoader(train_dataset,batch_size=8,shuffle=True,drop_last=True,collate_fn=collate_fn)




In [21]:
#自定义下游任务网络
#自定义网络使用单层的全连接层作为微调的下游任务网络，输入维度为768，输出维度为2，适用于二分类任务。通过在预训练模型的基础上添加一个全连接层，可以将预训练模型提取的特征映射到具体的分类标签，从而实现文本分类等下游任务。

#根据实际经验，自定义的微调网络参数总数应该大于0.5倍的预训练模型参数总数，以确保微调网络具有足够的容量来学习下游任务的特征和模式。对于BERT-base模型，预训练模型的参数总数约为110M，因此自定义的微调网络参数总数应该大于55M，以便能够有效地适应下游任务的需求并提高模型的性能。

import torch.nn as nn

#定义微调网络
class FinetuningModel(nn.Module):
    def __init__(self):
        super().__init__()

        #定义全连接层
        self.fc=nn.Linear(768,2) #使用2分类
    def forward(self,input_ids,attention_mask,token_type_ids):

        #获取bert模型的输出
        out=bert_model(input_ids=input_ids,attention_mask=attention_mask,token_type_ids=token_type_ids)

        #经过全连接层
        out=self.fc(out.pooler_output) #取出pooler_output作为全连接层的输入，pooler_output是BERT模型输出的一个特殊向量，通常用于文本分类等任务。通过将pooler_output传递给全连接层，可以将预训练模型提取的特征映射到具体的分类标签，从而实现文本分类等下游任务。

        return out




In [11]:
#测试
model=FinetuningModel()
model=model.to(device)
for input_ids,attention_mask,token_type_ids,labels in train_dataloader:
    print(model(input_ids=input_ids,attention_mask=attention_mask,token_type_ids=token_type_ids))

tensor([[ 0.2671, -0.2934],
        [ 0.3903, -0.1302],
        [ 0.6071, -0.4530],
        [ 0.2528, -0.1314],
        [ 0.2358, -0.2573],
        [ 0.1650, -0.4857],
        [ 0.2225, -0.7108],
        [ 0.4859, -0.3381]])
tensor([[ 0.4993, -0.8194],
        [ 0.4233, -0.7079],
        [ 0.2558, -0.5349],
        [ 0.5320, -0.4953],
        [ 0.1398, -0.4032],
        [ 0.3240, -0.2528],
        [ 0.3582, -0.2739],
        [ 0.1735, -0.6067]])
tensor([[ 0.2754, -0.2840],
        [ 0.3014, -0.9394],
        [ 0.1644, -0.2908],
        [ 0.6069, -0.4175],
        [ 0.2778, -0.1671],
        [ 0.3023, -0.1767],
        [ 0.2344, -0.0397],
        [ 0.2515, -0.0157]])
tensor([[ 0.3479, -0.0983],
        [ 0.2114, -0.2047],
        [ 0.3007, -0.2420],
        [ 0.2926, -0.3978],
        [ 0.4262, -0.3995],
        [ 0.3840, -0.5511],
        [ 0.2944, -0.1795],
        [ 0.3272, -0.4790]])
tensor([[ 0.0954, -0.4822],
        [ 0.3301, -0.3535],
        [ 0.3841, -0.3350],
        [ 0.2795

KeyboardInterrupt: 

In [22]:
#模型训练
model=FinetuningModel()
model=model.to(device)
optimizer=AdamW(model.parameters(),lr=2e-5,eps=1e-8)
criterion=nn.CrossEntropyLoss()

for param in bert_model.parameters():
    param.requires_grad=False #冻结预训练模型的参数不进行更新

epochs=3
model.train()


for epoch in range(epochs):
    start_time=time.time()
    train_dataloader=DataLoader(train_dataset,batch_size=8,shuffle=True,drop_last=True,collate_fn=collate_fn)

    total_loss,total_correct,total_samples,epoch_time=0,0,0,0

    for input_ids,attention_mask,token_type_ids,labels in train_dataloader:
        optimizer.zero_grad()
        input_ids=input_ids.to(device)
        attention_mask=attention_mask.to(device)
        token_type_ids=token_type_ids.to(device)
        labels=labels.to(device)
        out=model(input_ids,attention_mask,token_type_ids) #将输入数据传递给微调模型，获取模型的输出结果。通过调用模型的前向传播方法，可以获得文本分类的结果，从而进行后续的分析和应用。
        loss =criterion(out,labels)
        loss.backward() #计算损失函数的梯度，以便进行参数更新。通过调用loss.backward()方法，模型会自动计算出损失函数相对于模型参数的梯度，并将这些梯度存储在模型参数的.grad属性中。这样，在后续的优化步骤中，可以使用这些梯度来更新模型的参数，从而最小化损失函数并提高模型的性能。
        optimizer.step()
        total_samples += labels.size(0)
        total_loss+=loss.item()*input_ids.size(0)
        total_correct+=(torch.argmax(out,dim=-1)==labels).sum().item() #计算当前批次中模型预测正确的样本数量，并将其累加到total_correct变量中。通过比较模型的预测结果（torch.argmax(out, dim=-1)）与真实标签（labels），可以得到一个布尔张量，其中True表示预测正确，False表示预测错误。通过调用sum()方法，可以计算出当前批次中预测正确的样本数量，并将其累加到total_correct变量中，以便在整个训练过程中统计模型的准确性。
    end_time=time.time()
    epoch_time=end_time-start_time
    accuracy=total_correct*1.0/total_samples
    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/total_samples:.4f}, Accuracy: {accuracy:.4f}, Time: {epoch_time:.2f}s")

    #云服务器训练准确率在0.85左右，训练时间每轮为90秒左右，训练完成后可以进行模型评估和保存等后续操作，以便在实际应用中使用微调后的模型。

D:\Anaconda_envs\envs\aitest01\lib\site-packages\transformers\optimization.py:640: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


KeyboardInterrupt: 